### ISSUE TITLE
Logistics Tracking

### ISSUE THREAD

**Issue by paigetech** [osbridge/planning#289]
**Current In Progress/Pending**
- [x] Bathrooms, asking Facilities for extra info/issues
- [x] Getting Map from Facilities to use for Event Map

**Backlog**

Pre Event:
- [x] Food for Volunteers (pending by budget)
- [x] Video Recording (pending budget)
- [x] Power/AV needs
- [x] Moving Company Booking
- [x] Gather list of supply needs from other committees
- [x] ~~Food service licensing/volunteers~~
- [x] Work with donors to assess and accommodate their needs onsite (IE a booth in the hacker lounge)
- [x] Check in with Hacker Lounge Committee 
- [x] Check in Seamless about audio recording.
- [x] Signage for crowd funding campaign
- [x] Maps for bathrooms
- [x] Signage for bathrooms both gender and OS Bridge Branding
- [x] Check with Scheduling from Speaker people
- [x] Update First Aid Kit (Monday @ Conf?)
- [x] White Board in Hacker Lounge for lunch buddy finding
- [x] Coverage for A20? outdoor windows
- [x] Do room assignment for schedule
- [x] Add room assignments to website
- [x] Handle Speaker Questions and Requests about setup
- [x] Maps to food
- [x] Quite Room Sign

**Comment by christi3k** [comment]
Regarding the map: Take a look at what's in Dropbox for what we've used in prior years. As I recall, we ended up creating or modifying a map since First Unitarian didn't have a great one.

**Comment by shawnacscott** [comment]
Note from @kcomandich:

"Mike Gebhardt is who did video for us before Confreaks:
http://brytcast.com/

If you haven't yet, I'd have someone send notes to Stephouse and Seamless with the conference dates, just to make sure they have OSB on their calendars.

Wouldn't hurt to email Rob the organist too.
Robert Fishel <rwfishel@gmail.com>"

Also, @capnleela suggested hiring movers is something we need to have happen soon.

**Comment by paigetech** [comment]
4-24-16 update, followed up with Jason Chapman <JChapman@firstunitarianportland.org> about maps, initial email went unanswered. He has replied and promised maps by tomorrow.

**Comment by paigetech** [comment]
Maps have been received! They are now located in the google drive in DWG and PDF format, along with maps from previous years that were dug up.

**Comment by elea** [comment]
Emailed Paul Searle about Fair Play video possibly being involved, will update if/when I hear back.

**Comment by paigetech** [comment]
Have a request out with Jupiter Broadcasting to do the Keynotes at least.

Also the quote from Pacific North West came in at like 4k, and the major concern was it didn't include any editing, which it sounds like Swenson and I would be able to do, so that may be a "budget" option if there is money but not a ton.

**Comment by swenson** [comment]
Video editing party!

**Comment by paigetech** [comment]
- Called Stephouse, their event specialist will be calling me back. Last year's contract has 50% payment due 30 days out.
- Called Seamless, they will also be having someone call back.

**Comment by paigetech** [comment]
Quote for this year from Seamless.
[serq1833.pdf](https://github.com/osbridge/planning/files/255644/serq1833.pdf)

**Comment by paigetech** [comment]
@shawnacscott what's the deal with the organist? there's organ music at the conference?

**Comment by paigetech** [comment]
Does anyone know which rooms had ethernet drops last year? was it just for Keynote?

**Comment by kcomandich** [comment]
@paigetech The organist plays before the three morning keynotes. He charges $150 total. We often ask the keynote speakers if they have any specific requests for him to play.
Also, one of our registration questions is if people have specific requests. I've passed those requests along to him but just as suggestions.
Here are some things he played in 2014: https://youtu.be/QDD-8cAJWnE?t=8m21s

**Comment by capnleela** [comment]
We didn't have livestreaming for the keynotes last year, so no drop there,
I believe. If we had any drops, there might have been one in the speaker
preparation room.

There should be a record of what we ordered from Seamless in their records.

**Comment by paigetech** [comment]
@capnleela there is a record of what we had, which included 3 drops, but not where, which is what they are asking for. how about the password protected?

**Comment by shawnacscott** [comment]
I don't believe that the network was password protected, and my keychain shows no network for the conference. Is there a difference in price? Or will we not know until we fill out the form?

**Comment by paigetech** [comment]
I have requested that the quote include with/without a second password protected network.
Also asking for with/without ethernet drops at podiums since we aren't sure where they went last time.

**Comment by kcomandich** [comment]
Ah, we just got an email to info@opensourcebridge.org from Rob. He won't be able to play the organ for us. Bummer. Anybody know another organist??

> I'm Rob Fishel, the organist who has entertained before keynote addresses at OSB the last several years. I just wanted to let you know that I will not be available to play this year, and based on current plans, my availability in future years is doubtful.
> 
> Thank you for welcoming me in the past. I've enjoyed appearing before your attendees.
>

**Comment by paigetech** [comment]
Reply from Holli about the bathrooms:

There is a private bathroom right next to A108 that works really well as the gender neutral bathroom.  The bathrooms on the lower level are one stall restrooms as well, although those are designated for use by the Family Shelter, so not the best ones to offer your participants.
