### ISSUE TITLE
💡 Brainstorm ideas for volunteer recruitment to work on-site

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#358]
- [ ] in-person promo meetings - #359
- [ ] flyers for schools - #360
- [ ] email boilerplate for people to pass on - #361
- …?

**Comment by gabelula** [comment]
I'm assigning many people to this ticket as it seems that is a "brainstorm ideas" kind of tickets. If people have ideas for on-site volunteer recruiment, add it here.

**Comment by thejensen** [comment]
Hi! What do you mean by on-site recruitment? Say, people already showed up to the conference and we want them to volunteer later that day, tomorrow, or volunteer next year?

**Comment by reidab** [comment]
@thejensen oops — it's not the recruitment that's on-site, it's recruitment (before the event) for tasks that happen on-site

**Comment by gabelula** [comment]
What about 

[] email people that volunteered other years

?

**Comment by gabelula** [comment]
Other ticket related: https://github.com/osbridge/planning/issues/369

**Comment by gabelula** [comment]
This ticket about flyers to get volunteers https://github.com/osbridge/planning/issues/369
